# Generated by Django 2.0.7 on 2018-07-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20180717_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-update']},
        ),
        migrations.AddField(
            model_name='thread',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
