# Generated by Django 2.1.3 on 2018-11-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_auto_20181117_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadosInversiones',
        ),
    ]
