# Generated by Django 2.1.3 on 2018-11-17 11:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_delete_estadosinversiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversionistassolicitudes',
            name='estado',
            field=models.CharField(choices=[('s', 'Solicitado'), ('a', 'Aceptado'), ('r', 'Rechazado'), ('t', 'Inversión retornada'), ('z', 'Inversión realizada'), ('m', 'Inversión en mora')], default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('a', 'Aceptado'), ('r', 'Rechazado'), ('p', 'Proceso')], default='p', max_length=1),
        ),
    ]
