# Generated by Django 2.1.3 on 2018-11-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_auto_20181117_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='nivelDeRiesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prestamos.NivelesDeRiesgo'),
        ),
    ]
