# Generated by Django 2.1.3 on 2018-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_auto_20181117_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='valor_Faltante',
            field=models.IntegerField(),
        ),
    ]
