# Generated by Django 2.1.3 on 2018-11-17 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_auto_20181117_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
