# Generated by Django 2.1.3 on 2018-11-17 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_auto_20181117_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesparametros',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_parametros', to='prestamos.Solicitudes'),
        ),
    ]
