# Generated by Django 2.1.3 on 2018-11-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181117_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, default=1, null=True),
        ),
    ]
